// let fruit = ["apple", "Banana", "orange", "BANANA"];
// console.log(fruit);

// console.log(fruit[0]);

// fruit[0] = "coconut";

// console.log(fruit);

// fruit.push("ASASAS");

// console.log(fruit);

// fruit.pop();
// console.log(fruit); // removing first

// fruit.unshift("apple");  //Adding first
// console.log(fruit);

// fruit.shift("Banana");
// console.log(fruit);


let fruit = ["apple", "Banana", "orange", "BANANA"];
for (let i = 0; i < fruit.length; i++) {
    console.log(fruit[i]);
}